services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - activity-logger
  
  activity-logger:
    build: ./activitylogger
    ports:
      - "4002:4002"
    env_file:
      - ./backend/.env