FROM node:20-alpine AS baseimage
WORKDIR /app
COPY package*.json /app/
RUN npm install 
COPY . .
RUN npm run build


FROM node:20-alpine
WORKDIR /app
# Install serve globally to serve static files
RUN npm install -g serve
COPY --from=baseimage /app/build ./build
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]


