name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  
  file_changed:
    runs-on: ubuntu-latest
    
    outputs:
      frontend:  ${{ steps.filter.outputs.frontend}}
      backend:  ${{ steps.filter.outputs.backend}}
      logger:  ${{ steps.filter.outputs.logger}}
    steps:
    - name: checkout
      id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: | 
          frontend:
            - 'frotend/frontend/**'
          backend:
            - 'backend/**'
          logger:
            - 'activitylogger/**'
          
        
    
  name: install frontend
  runs-on: ubuntu-latest
  depends-on: file_changed
  if: {{ file_changed.outputs.frontend == 'true'}}
  steps:
    - name: checkout and build frontend
      run: | 
        echo "frontend changes detected""
        cd frotend/frontend
        ls -la
        npm install
        npm run build   
