name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        sparse-checkout: webcare/frotend/frontend
    - name : version
      run: |
         node --version
    - name: install 
      run: | 
        ls -la
        npm run install
        npm run build   
