name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: install 
      run: | 
        cd frotend/frontend
        ls -la
        npm install
        npm run build   
